export type Trade = {
  id: string;
  tradeId: string;
  tradeNumber: number | null;
  account: string[];
  dateTime: string | null;
  day: string | null;
  pair: string | null;
  position: string | null;
  netEur: number | null;
  accountBalance: number | null;
  rMultiple: number | null;
  setup: string[];
  tfType: string[];
  algorithm: string[];
  sessionTime: string[];
  liquiditySweep: boolean;
  dxy: boolean;
  delta: boolean;
  fractalShift: boolean;
  lastEditedTime: string | null;
};
export type Outcome = 'win' | 'loss' | 'breakeven';
export type Comparison = {label: string; group: 'Setup'|'Confluence'; count:number; wins:number; avgPnl:number; totalPnl:number; winRate:number};
export type TimePerformance = {label:string;count:number;wins:number;winRate:number;avgPnl:number};
export type BalancePoint = {time: string; value: number};
export type Performance = {
  total: number; closed: number; wins: number; losses: number; breakeven: number;
  winRate: number; netPnl:number; avgPnl:number; grossProfit:number; grossLoss:number;
  profitFactor:number|null; avgR:number|null; bestTrade:number|null; worstTrade:number|null;
  maxDrawdown:number; maxDrawdownPct:number|null;
  cumulative:BalancePoint[]; balance:BalancePoint[];
  comparisons:Comparison[]; sessions:TimePerformance[]; weekdays:TimePerformance[]; hours:TimePerformance[];
  monthly:TimePerformance[];
};
export type SyncStatus = {lastSyncedAt:string|null; lastError:string|null; lastCount:number; state:string};
export type DashboardView = 'overview' | 'journal' | 'calendar' | 'analytics';
export type DashboardPayload = {view:DashboardView; demo:boolean; today:string; generatedAt:string; timeZone:string; performance:Performance; trades:Trade[]; status:SyncStatus|null; lastTradeDate:string|null; selectedAccount:string; selectedPeriod:string};
